---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
    version: lts
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: jenkins
    version: lts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
    version: lts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
      version: lts
  template:
    metadata:
      labels:
        app: jenkins
        version: lts
    spec:
      containers:
      - name: jenkins-master
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
          name: http

